ood_dataset:
  name: hyperkvasir_ood
  num_classes: 6

  dataset_class: ImglistDataset
  interpolation: bilinear
  batch_size: 32
  shuffle: False

  image_size: 224
  pre_size: 256
  num_workers: '@{num_workers}'
  num_gpus: '@{num_gpus}'
  num_machines: '@{num_machines}'
  split_names: [val, nearood, farood]
  val:
    data_dir: ./data/images_largescale/
    imglist_pth: ./data/benchmark_imglist/hyperkvasir/val_lower.txt
  nearood:
    datasets: [lower, upper]
    lower:
      data_dir: ./data/images_largescale/
      imglist_pth: ./data/benchmark_imglist/hyperkvasir/test_upper.txt
    upper:
      data_dir: ./data/images_largescale/
      imglist_pth: ./data/benchmark_imglist/imagenet/test_lower.txt
  farood:
    datasets: [mnist, svhn, texture, place365]
    mnist:
      data_dir: ./data/images_classic/
      imglist_pth: ./data/benchmark_imglist/cifar10/test_mnist.txt
    svhn:
      data_dir: ./data/images_classic/
      imglist_pth: ./data/benchmark_imglist/cifar10/test_svhn.txt
    texture:
      data_dir: ./data/images_classic/
      imglist_pth: ./data/benchmark_imglist/cifar10/test_texture.txt
    place365:
      data_dir: ./data/images_classic/
      imglist_pth: ./data/benchmark_imglist/cifar10/test_places365.txt
